#!/bin/bash

pkgs=(
    git@github.com:notarealdeveloper/callable_module
    git@github.com:notarealdeveloper/signalhandlers
    git@github.com:notarealdeveloper/interprocess
    git@github.com:notarealdeveloper/is_instance
    git@github.com:notarealdeveloper/executive
    git@github.com:notarealdeveloper/assure
    git@github.com:notarealdeveloper/babel
    git@github.com:notarealdeveloper/webfs
    git@github.com:notarealdeveloper/kern
    git@github.com:notarealdeveloper/mmry
    git@github.com:notarealdeveloper/embd
    git@github.com:notarealdeveloper/wnix
)

bootstrap() {
    mkdir -pv src
    pushd src >/dev/null
    for pkg in "${pkgs[@]}"; do
        dst="$(basename "$pkg")"
        if [[ ! -d "$dst" ]]; then
            git clone "$pkg"
        fi
    done
    popd >/dev/null
}

if [[ -z $1 || ! -d src ]]; then
    bootstrap
    exit 0
fi

pushd src >/dev/null
for pkg in *; do
    pushd "$pkg" >/dev/null
    echo "================="
    echo "# $pkg"
    $@
    popd >/dev/null
done
popd >/dev/null
echo "================="
