#!/bin/bash

pkgs=(
    https://github.com/notarealdeveloper/callable_module
    https://github.com/notarealdeveloper/is_instance
    https://github.com/notarealdeveloper/assure
    https://github.com/notarealdeveloper/mmry
    https://github.com/notarealdeveloper/embd
    https://github.com/notarealdeveloper/wnix
)

bootstrap() {
    mkdir -pv src
    pushd src >/dev/null
    for pkg in "${pkgs[@]}"; do
        dst="$(basename "$pkg")"
        if [[ ! -d "$dst" ]]; then
            git clone "$pkg"
        fi
    done
    popd >/dev/null
}

if [[ -z $1 || ! -d src ]]; then
    bootstrap
    exit 0
fi

pushd src >/dev/null
for pkg in *; do
    pushd "$pkg" >/dev/null
    $@
    popd >/dev/null
done
popd >/dev/null
