#!/bin/bash

pkgs=(
    https://github.com/notarealdeveloper/callable_module
    https://github.com/notarealdeveloper/is_instance
    https://github.com/notarealdeveloper/assure
    https://github.com/notarealdeveloper/mmry
    https://github.com/notarealdeveloper/embd
    https://github.com/notarealdeveloper/wnix
)

bootstrap() {
    mkdir -pv src
    pushd src
    for pkg in "${pkgs[@]}"; do
        git clone "$pkg"
    done
    popd
}

if [[ -z $1 || ! -d src ]]; then
    bootstrap
    exit 0
fi

pushd src
for pkg in *; do
    pushd "$pkg"
    $@
    popd
done
popd
