#!/bin/bash

bootstrap() {
    pkgs=($(cat packages.txt))
    mkdir -pv src
    pushd src
    for pkg in "${pkgs[@]}"; do
        git clone "$pkg"
    done
    popd
}

if [[ -z $1 || ! -d src ]]; then
    bootstrap
    exit 0
fi

pushd src
for pkg in *; do
    pushd "$pkg"
    $@
    popd
done
popd
